[supabase]
url = "https://rfxybwtkaegzchmarlxy.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmeHlid3RrYWVnemNobWFybHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODU3OTMsImV4cCI6MjA2NTE2MTc5M30.zx4EQg4e8Sksn53x2lWzAemoOHzhVigh3VaCXXncyHA"

AZURE_AI_SEARCH_ENDPOINT="https://bruhhhhhhhhhhh.search.windows.net"
AZURE_AI_SEARCH_KEY="vSpy1K113Gb5tmgpkyoM9COK2xz2TrPZb7uB3RRbGNAzSeAu8dzM"
AZURE_AI_SEARCH_INDEX_NAME="group5-rfp-turbo-index"

AZURE_OPENAI_ENDPOINT="https://rfpdocumentanalyser.openai.azure.com/"
AZURE_OPENAI_API_KEY="FNMJ501iRVVvQe2t97zMA2lujBPswdhRK9tpaovV6hBhYlTzW0tpJQQJ99BFACYeBjFXJ3w3AAABACOG02lG"
AZURE_OPENAI_API_VERSION="2024-02-15-preview"
AZURE_OPENAI_EMBEDDING_DEPLOYMENT="group5-embedding-turbo"
AZURE_OPENAI_CHAT_DEPLOYMENT="gpt-4.1-mini"

AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT="https://bruhh.cognitiveservices.azure.com/"
AZURE_DOCUMENT_INTELLIGENCE_KEY="NpF7hGsUBXV96e8lUpYbW4dKMirWZaJZU5e5mXpJH9MOKanT51hvJQQJ99BEACYeBjFXJ3w3AAALACOGobw4"


